In [1]:
import numpy as np

In [3]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket indexing and selection

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

In [7]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
slice_of_arr=arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [12]:
arr_copy=arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [13]:
arr_copy[1:4]=98
arr_copy

array([99, 98, 98, 98, 99, 99,  6,  7,  8,  9, 10])

In [14]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## 2d array(matrices)

In [16]:
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr_2d[1]

array([20, 25, 30])

In [18]:
arr_2d[1,0]

20

In [19]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [20]:
arr_2d[2,:]

array([35, 40, 45])

## selection

In [21]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [23]:
bool_arr=arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [24]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [25]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
x=2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])