In [1]:
import numpy as np

## Creating Numpy Arrays

In [2]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### arange

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### ones

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### eye
#### creates an identity matrix

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random

#### rand - Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [16]:
np.random.rand(2)

array([0.37729898, 0.9536159 ])

In [18]:
np.random.rand(5,5)

array([[0.0190416 , 0.11033099, 0.30142561, 0.39367352, 0.78202643],
       [0.17856941, 0.99595872, 0.88738626, 0.36729035, 0.88276545],
       [0.1652578 , 0.73696231, 0.61056889, 0.96475739, 0.9977778 ],
       [0.0743128 , 0.39255693, 0.29095378, 0.62287905, 0.52962184],
       [0.67880887, 0.74456125, 0.80783197, 0.05093422, 0.25329969]])

## randn

In [19]:
np.random.randn(4)

array([-0.38061183,  1.42354548,  0.15477616,  1.43656225])

In [20]:
np.random.randn(5,5)

array([[ 0.48413022, -0.31199578,  0.56711511, -0.92213432,  0.68037484],
       [-0.86916863,  0.27659512, -2.13407352,  0.18686509,  0.78377182],
       [-1.30781441,  1.28402426,  1.99070382,  0.46554699,  0.16323753],
       [ 0.39054213, -0.21038242, -0.37746652, -0.14473156, -0.13638164],
       [-1.12526742,  0.62814088, -0.35831766,  0.32986832,  0.19815679]])

## randint

In [21]:
np.random.randint(1,100)

23

In [22]:
np.random.randint(1,100,10)

array([35,  4, 68, 27, 29, 26, 47, 77, 80, 74])

In [23]:
arr=np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr=np.random.randint(0,50,10)

In [26]:
ranarr

array([25,  7, 39, 46,  0, 25, 22, 37,  6, 23])

## Reshape

In [27]:
arr.shape

(25,)

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
arr.reshape(5,5).shape

(5, 5)

## max,min

In [31]:
ranarr

array([25,  7, 39, 46,  0, 25, 22, 37,  6, 23])

In [32]:
ranarr.max()

46

In [33]:
ranarr.min()

0

In [34]:
ranarr.argmax()

3

In [35]:
ranarr.argmin()

4

In [38]:
arr.dtype

dtype('int32')